# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
[plugins.zsh-vi-mode.hooks]
post = """
zvm_bindkey viins '^j' autosuggest-accept

function my_space_completion() {
  abbr-expand-and-insert && _zsh_autosuggest_fetch_suggestion
}

zvm_define_widget my_space_completion
zvm_bindkey viins ' '  my_space_completion
# zvm_bindkey viins ' ' abbr-expand-and-insert
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
proto = "ssh"
use = ["{{ name }}.zsh"]
[plugins.zsh-autosuggestions.hooks]
pre = """
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
"""

# [plugins.zsh-abbr]
# github = "olets/zsh-abbr"
# proto = "https"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
proto = "ssh"
# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
